spring:
  application:
    name: accouont-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

server:
  port: 8080
logging:
  level:
    com.github: debug
